
```{r}
historical_fp_data |> 
    filter(
        org_unit == "Kenya",
        analytic_name == "COCs"
    )
```


```{r}
anomalies_sample <- historical_fp_data |> 
    unite("id", analytic_name, org_unit, method,  sep = "__") |> 
    filter(id == "COCs__Kenya__Service") |> 
    anomalize(period, value) 

anomalies_sample |> 
    plot_anomalies_cleaned(period)
```



```{r}
sample_prophet_model_output_data <- readRDS("data/sample_prophet_model_output_data.rds")
sample_prophet_model_input_data <- readRDS("data/sample_prophet_model_input_data.rds")
```


```{r}
combined_input_output_data <- sample_prophet_model_input_data |> 
    bind_rows(
        sample_prophet_model_output_data |> select(ds, yhat_lower, yhat_upper, yhat)
    ) |>
    pivot_longer(cols = contains("y"), names_to = "metric", values_to = "value") 

!"ds" %in% colnames(combined_input_output_data) & !"y" %in% colnames(combined_input_output_data)
```

```{r}
suppressMessages(
    combined_input_output_data |> 
    filter(!is.na(y)) |> 
    select(ds, y) |> 
    head(1) |> 
    forecast_with_prophet(12, "flat", T)
)

```









```{r}
combined_input_output_data |>
    summarise(across(2:last_col(),  ~sum(.x, na.rm = TRUE)))
    
```



```{r}
test_orgs <- extract_metadata_units("mikonya", "Kenya2030")

con_elements <- readRDS("data/fp_consumption_data_element_ids.rds")
ser_elements <- readRDS("data/fp_service_data_element_ids.rds")
county_and_country_ids <- readRDS("data/level_1_2_ids.rds")
```




```{r}
res <- GET("https://hiskenya.org/", authenticate("mikonya", "Kenya20dff30"))

b_url <- "https://hiskenya.org/"
```


```{r}
# Generate a sequence of dates from January 2020 to January 2024
dates <- seq(from = as.Date("2024-01-01"), to = as.Date("2024-05-01"), by = "month")

# Format the dates as "YYYYMM"
formatted_dates <- format(dates, "%Y%m")

# Display the result
formatted_dates

```


```{r}
his_con <- Dhis2r$new(base_url = b_url, username = "mikonya", password =  "Kenya2030")

response <- his_con$get_analytics(
    analytic = c(con_elements[1], con_elements[2]),
    org_unit = county_and_country_ids[1],
    period = c(formatted_dates),
    output_scheme = "NAME"
)

class(con_elements)
```



```{r}
forecast_results |> 
    filter(
        analytic_name == "2 Rod", org_unit == "Kenya"
    ) |>
    retrieve_model_info(fp_method = "Consumption")
```













































